# Miyadaiku config file

# Base URL of the site
site_url: https:/www.example.com

# Title of the site
site_title: Sample blog
site_description: Blog by example
# site_keywords:

# Default language code
lang: ja

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

copyright: Copyright Â© 2020 example.

# favicon: /static/icons/...

# og_image:
# twitter_card: summary
# og_description:

twitter_name: example
github_name: github
# custom_search_engine_id:

# ga_tracking_id: UA-...

# List of site theme
themes:
  - aoirint_miyadaiku_theme_blog
